# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('telefono', models.CharField(max_length=100)),
                ('tipo_cita', models.CharField(max_length=100)),
                ('dia', models.DateField(help_text='dia del evento', verbose_name='Dia del evento')),
                ('inicio_cita', models.TimeField(help_text='inicio de la cita', verbose_name='Inicio cita')),
                ('finaliza_cita', models.TimeField(help_text='Finalizacion de la cita', verbose_name='Cita Final')),
                ('nota', models.TextField(blank=True, help_text='Textual Notes', null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
    ]
