# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-11 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_auto_20180210_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='dia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='citas',
            name='finaliza_cita',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='citas',
            name='inicio_cita',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='citas',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
    ]
